FROM ubuntu:focal

RUN apt-get update
RUN apt-get install -y curl
RUN curl -s https://packagecloud.io/install/repositories/emqx/emqx/script.deb.sh | bash
RUN apt-get update
RUN apt-get install emqx=5.0.20

